### ISSUE TITLE
Upgrade to the new version of YamlDotNet (9.1.0)

### ISSUE THREAD

**Issue by Debbus72** [nbarbettini/FlexibleConfiguration#14]
This project uses "still" version 8.1.0 of YamlDotNet. As YamlDotNet is now at version 9.1.0 and is not backward compatible, but other packages/libraries are upgrading to 9.1.0 there are conflicts with using FlexibleConfiguration. 

So if you would please upgrade to the latest version of YamlDotNet that would be very helpful for us. 
https://github.com/aksoftware98/multilanguages/issues/17

**Comment by nbarbettini** [comment]
Hey @Debbus72, sorry for the delay. I unfortunately don't have time to maintain this library right now, but if you or @laura-rodriguez want to create a PR for the YamlDotNet version change, I would be happy to merge it.

**Comment by nbarbettini** [comment]
Thanks to @tobindh's help in #15, I published [FlexibleConfiguration 2.0.0](https://www.nuget.org/packages/FlexibleConfiguration/2.0.0) on Nuget. I bumped the major version number because YamlDotNet was upgraded from v8 to v11, but that is the only change.

@Debbus72 If you need YamlDotNet v9 specifically, and v11 does not work for you, copy this code directly into your solution and adjust as needed.

I do recommend moving to [Configuration Providers](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers) whenever possible. FlexibleConfiguration is based on a very old fork of the code that eventually became Configuration Providers. The official APIs are now much newer and better than FlexibleConfiguration!
